package chibivaru.additionalrecipe.common;

import static chibivaru.additionalrecipe.AdditionalRecipe.*;

import cpw.mods.fml.common.ModMetadata;

public class ARModInfo
{
	public static void loadInfo(ModMetadata meta)
	{
		meta.modId = MODID;
		meta.name = MODNAME;
		meta.description ="This mod adds New Recipe and POWERFUL WEAPONS and INSANE ARMORS for Minecraft.";
		meta.version = VERSION ;
		meta.url = "http://chaostcg31.blog.fc2.com/";
		meta.authorList.add("chibivaru");
		meta.credits = "shion ch,schr0,defeatedcrow,a1lic";
		//meta.logoFile ="assets/aluminiummod/logo.png";
		meta.logoFile = "";
		meta.autogenerated = false;
	}

}
